name: Tests

on:
  push:
    branches:
      - master
    paths:
      - '**.py' # only run workflow when source files changed
  pull_request:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout MNF repo
        uses: actions/checkout@v2
        with:
          repository: janosh/torch-mnf
          path: torch-mnf

      - name: Set up latest Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # install torch first as torch_scatter needs it, torchvision for torch-mnf
          pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html
          pip install -r requirements.txt
          pip install .
          pip install seaborn # required by torch-mnf
          pip install -e $GITHUB_WORKSPACE/torch-mnf

      - name: Run Tests
        run: |
          python -m pytest --ignore=torch-mnf
